apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyborch-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyborch-com
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: cyborch-com
    spec:
      containers:
      - name: cyborch-com
        image: cyborch/cyborch-com:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
        ports:
        - containerPort: 80
