apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cyborch-com-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: cyborch.com
    http:
      paths:
      - backend:
          serviceName: cyborch-com
          servicePort: 80
