apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cyborch-com-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - cyborch.com
    secretName: cyborch-com-tls
  rules:
  - host: cyborch.com
    http:
      paths:
      - backend:
          serviceName: cyborch-com
          servicePort: 80
