apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cyborch-com-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cyborch.com
    secretName: cyborch-com-tls
  rules:
  - host: cyborch.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cyborch-com
            port:
              number: 80
